import './globals.css';

import { ClerkProvider } from '@clerk/nextjs';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en" className="dark">
        <head>
          <title>AdSend Dashboard</title>
          <meta name="description" content="Manage properties, pages, containers, and banners for ad injection with AdSend. Test ad injection in a realistic car marketplace layout." />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </head>
        <body className="bg-gray-950 text-gray-100 min-h-screen dark:bg-gray-950 dark:text-gray-100">
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}
